package com.salesianostriana.cuadromandointegralgrupo2.cuadromandointegralgrupo2.servicio;

import com.salesianostriana.cuadromandointegralgrupo2.cuadromandointegralgrupo2.proceso.model.IndicadorUnidad;
import com.salesianostriana.cuadromandointegralgrupo2.cuadromandointegralgrupo2.repositorio.proceso.IndicadorUnidadRepository;

public class IndicadorUnidadServicio extends ServicioBase<IndicadorUnidad, Long, IndicadorUnidadRepository> {

}
