package com.salesianostriana.cuadromandointegralgrupo2.cuadromandointegralgrupo2.servicio;

import com.salesianostriana.cuadromandointegralgrupo2.cuadromandointegralgrupo2.proceso.model.IndicadorCentro;
import com.salesianostriana.cuadromandointegralgrupo2.cuadromandointegralgrupo2.repositorio.proceso.IndicadorCentroRepository;

public class IndicadorCentroServicio extends ServicioBase<IndicadorCentro, Long, IndicadorCentroRepository> {

}
