package com.salesianostriana.cuadromandointegralgrupo2.cuadromandointegralgrupo2.servicio;

import com.salesianostriana.cuadromandointegralgrupo2.cuadromandointegralgrupo2.proceso.model.PuntoControl;
import com.salesianostriana.cuadromandointegralgrupo2.cuadromandointegralgrupo2.repositorio.proceso.PuntoControlRepository;

public class PuntoControlServicio extends ServicioBase<PuntoControl, Long, PuntoControlRepository> {

}
